### ISSUE TITLE
Multiple select

### ISSUE THREAD

**Issue by maxjust** [vestman/Select-or-Die#1]
Hello, it`s a really cool plugin. Better select what I see. But it need to multiselect. Very need. Can you, please, do it.
Thanks in advance.  and sorry for my English...

**Comment by vestman** [comment]
Let me take a look at it!

**Comment by tedmcdo** [comment]
I second the call for multiselect (with submit and cancel options, preferably). Amazing plugin by the way, best I have seen yet.

**Comment by thers** [comment]
Agree w/ folks, awesome plugin, best native select replacer, and it will be godlike with multiple option ;)

**Comment by vestman** [comment]
I haven't forgotten you... Working on it.

**Comment by vestman** [comment]
I'm closing this since it's not really an "issue". I still have it on my todo list and I'll let you guys know when I've implemented it!
