### ISSUE TITLE
Dropdown not activating if the parent container is hidden on page load.

### ISSUE THREAD

**Issue by rarewave** [vestman/Select-or-Die#13]
Hi, I seem to have encountered an issue where the select menu is not opening up when you load the page with the parent container hidden. 

I'm using jquery's slideToggle();  from a click event to show the form with the selectordie inside it. There are no errors in the console.

If on the otherhand, the parent container is display: block on the page load, SoD functions perfectly.

Thanks

**Comment by vestman** [comment]
In what browser are you experiencing this? I've just tested this - http://jsfiddle.net/vestman/zhnsyong/ - in IE9 (Win7 using Parallels), Firefox (on a Mac) and Chrome (on a Mac).

**Comment by vestman** [comment]
I'm closing this since I'm not able to reproduce the issue and the lack of response. @rarewave, just reopen this issue if you still encounter this issue.

**Comment by steveoliveira** [comment]
I also had that problem but the difference is that i had the option "size:5" on the config of the select, and for that reason the select wouldn't open - http://jsfiddle.net/zhnsyong/5/
Removing the "size" in the config resolves the problem, hope it helps anyone with this similar problem.
