### ISSUE TITLE
IE9/IE10 not working

### ISSUE THREAD

**Issue by FlorentBiffi** [vestman/Select-or-Die#14]
Hi, 
I tested your plugin on IE9 and IE10 from your website (http://vst.mn/selectordie/) and I noticed that it doesn't work. Indeed when I change the active option the select won't update.

And in your compability section you wrote it works on IE8+.

Do you have any issues?

**Comment by ghost** [comment]
Me too.
This isn´t update when i change the option. I used jQuery 1.8 and 1.10 both don't work.

**Comment by ghost** [comment]
This was fixed by another user.  Issue #7  Check out cah4a@2d5e057

**Comment by FlorentBiffi** [comment]
Ok, thank you.

**Comment by vestman** [comment]
Fixed! Thanks, @cah4a and @mcaskill!

**Comment by ghost** [comment]
thank you

**Comment by cah4a** [comment]
You're welcome!

**Comment by kapunakap** [comment]
That fixed it. many great.
