### ISSUE TITLE
Only first <option in every <select> is selectable in IE

### ISSUE THREAD

**Issue by MiejskiPartyzant** [vestman/Select-or-Die#16]
I have a strange issue on IE (IE11, IE10, IE9 and IE8 ). When I try to select an option from the select it always selects the first possible option and I can't figure out the cause of it.

**Comment by vestman** [comment]
Would you mind updating the SoD to the latest version and see if the problem still exist after that.

**Comment by MiejskiPartyzant** [comment]
Updating the plugin did the trick, thank you.

**Comment by vestman** [comment]
Np!
