### ISSUE TITLE
Filterable option select

### ISSUE THREAD

**Issue by justiny** [vestman/Select-or-Die#18]
Hey,

Love your script.  Making some dumb mistake on implementing with a filterable list of options.  Do I need to add something to call in order to get it to trigger the filtered option when it has been selected? 

Thanks,
Justin

**Comment by vestman** [comment]
@justiny, what do you mean by _"order to get it to trigger the filtered option when it has been selected"_? Do you need to update the SoD after making a selection, or do you need something to happen when a selections has been made?

Take a look at the links below, they might be of help. If not, let me know...
http://vst.mn/selectordie/#callback
http://vst.mn/selectordie/#update

**Comment by vestman** [comment]
Closing this due to lack of response. Re-open this issue if you still need help, @justiny.
