### ISSUE TITLE
Prevent scrollbar click from closing dropdown in IE

### ISSUE THREAD

**Issue by lukechapman** [vestman/Select-or-Die#20]
Similar issue to a similar plugin found here: https://github.com/brianreavis/selectize.js/issues/182

Clicking on the scrollbar in IE (tested on IE8 and IE11) fires the blur event and closes the dropdown

**Comment by vestman** [comment]
Fixed (or at least I hope so). I've tested it in IE8, IE9, IE10 and IE11 using Parallels. Feel free to reopen it again if that's not the case...

**Comment by stefanlesik** [comment]
This is not working for me. Clicking the scrollbar closes dropdown  in IE8, IE9, IE10 and crashes browser in IE11

**Comment by vestman** [comment]
@stefanlesik, I just tried it again in IE8 (Win XP, Parallels), IE9 (Win 7, Parallels), IE10 (Win 7, Parallels) and IE11 (Win 8.1, Parallels). It works just fine for me. Are you experiencing this on the demo page or on a page where you've implemented the SoD?

**Comment by stefanlesik** [comment]
Apologies, this is fixed now. Thanks!
