### ISSUE TITLE
Using with mixitup

### ISSUE THREAD

**Issue by yantakus** [vestman/Select-or-Die#23]
I'm using [mixitup](https://mixitup.kunkalabs.com/) jQuery plugin for content filtering. It works good with plain selects: http://codepen.io/patrickkunka/pen/Fqocw
But when I use selectordie to customize the selects, mixitup stops working.

Here is how mixitup fires:

```
$filters.on('change', 'select', function(e){
    ...
});
```

How can I make it working?

**Comment by vestman** [comment]
@web2style, It looks like it's working just fine. I forked the pen and tested it in Chrome and Firefox on OSX: http://codepen.io/anon/pen/azzPwy

**Comment by yantakus** [comment]
Yes, it works. Sorry, my bad. Just had an unconnected with mixitup or selectordie mistake. Thanks for help!

**Comment by vestman** [comment]
Np, and thanks for checking out SoD!
