### ISSUE TITLE
Not functioning on Firefox 30.0

### ISSUE THREAD

**Issue by dbounce-io** [vestman/Select-or-Die#6]
Hi,

was implementing this in one project and saw today that the plugin does not seem to work on the latest version of Firefox 30.0.

Please check your plugin homepage for example: 
http://vst.mn/selectordie/

Otherwise, a great plugin, keep up the good work!

**Comment by vestman** [comment]
Hi,

Hm, I just tried it in FF 30.0 and FF Aurora 32.0a2 with no issues. What issues are you experiencing?

**Comment by dbounce-io** [comment]
Hi,

here are two issues with the select lists:

![image](https://cloud.githubusercontent.com/assets/3737757/3553684/4658b0fc-0906-11e4-97ca-18e771d7ba05.png)

The custom styling does not seem to work

**Comment by vestman** [comment]
Thanks!

You're running Win, right? I'll take a look at it as soon as possible!

**Comment by dbounce-io** [comment]
Yes, on Windows 7. Didnt try on my mac though.

**Comment by vestman** [comment]
I just tried it on Windows 7 in Firefox 30.0 (using Parallels) and it worked just fine. Do you get any errors in your console?

![skarmavbild 2014-07-11 kl 16 42 27](https://cloud.githubusercontent.com/assets/564243/3554041/bd690806-0909-11e4-96f6-f79a7470c125.png)

**Comment by dbounce-io** [comment]
Hi,

nope - no console log errors I'm afraid.

**Comment by mlumbroso** [comment]
Hello,

I've got the exact same issue with Chrome 36.0 in Win 8. Tell me if you need more details.

Thanks for all the nice work you are doing :+1:

**Comment by dbounce-io** [comment]
![sod_chrome_81](https://cloud.githubusercontent.com/assets/3737757/4073060/bf0653c0-2e8f-11e4-9c6c-c3a138386e47.png)
Hi again Per, same issue with Windows 8.1 - Chrome

And the issue still persists on Win7 Firefox as well (same version as I mentioned before).

**Comment by dbounce-io** [comment]
Chrome Version 36.0.1985.143 m

**Comment by vestman** [comment]
Fixed.
