### ISSUE TITLE
IOS selection reset issue

### ISSUE THREAD

**Issue by ghost** [vestman/Select-or-Die#8]
After you make a selection on IOS and click on another input field, it resets the selection.  

On your live demo site, it doesn't have this issue.  Maybe the current download is not up to date?

**Comment by mrtnpro** [comment]
+1 
Having the same issue

**Comment by mdsEu** [comment]
+1

I could not find solution

**Comment by HandHugs** [comment]
Same thing!

**Comment by HandHugs** [comment]
Anyone? This is basically un-usable if it doesn't work on mobile / ipad...

**Comment by andrew-knott** [comment]
+1 Same issue.

**Comment by claudiomedina** [comment]
It's happening on my PC too but only on Chrome, the other browsers work fine.

**Comment by andrew-knott** [comment]
If you copy the minified version from the selectordie site, it works.

http://vst.mn/selectordie/!inc/js/selectordie.min.js

Something must be up with the Bower version?

**Comment by PawelGIX** [comment]
I have this issue.

**Comment by vestman** [comment]
Fixed, thanks to @builtbylane! Sorry for taking so long to merge the fix.

**Comment by macstens** [comment]
The issue is resolved in the normal version of the script, but the minified version still has the problem... just to let anyone know.

**Comment by conair355** [comment]
I tried removing the class "touch" form the selectordie library, and it worked, able to see the custom dropdown style in iPad and also Android devices.

Search the code below and remove the class "touch" in line number: 98

if ( _private.isTouch() ) {
                            $sod.addClass("touch");
}

**Comment by jordanoverbye** [comment]
Anyone still having this issue?

**Comment by heeyblitz** [comment]
Yeap, you only need to replace 'touch' class on the min.js for anything else and works fine.
  }).insertAfter(this), h.isTouch() && u.addClass("touch"), v = a("<span/>", {
